[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.15.45"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.3"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"
