[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.uber.org/zap"
  version = "v1.9.1"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.43"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.15.0"
